name: flutter_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  device_info: ^2.0.0
  package_info: ^2.0.0
  badges: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  async: ^2.6.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  logger: ^1.0.0
  url_launcher: ^6.0.6
  webview_flutter: ^2.0.8
  injectable: ^1.4.0
  get_it: ^7.1.3
  freezed_annotation: ^0.14.2
  cupertino_icons: ^1.0.3
  vrouter: ^1.1.4+15
  firebase_remote_config: ^0.10.0+2
  flutter_form_builder: ^6.0.1
  equatable: ^2.0.3
  connectivity_plus: ^1.0.4
  chopper: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.3
  mockito: ^5.0.10
  bloc_test: ^8.0.2
  injectable_generator: ^1.4.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  chopper_generator: ^4.0.1

flutter:
  uses-material-design: true